### ISSUE TITLE
docker-py  doesn't seem to be installed error.

### ISSUE THREAD

**Issue by muradkablan** [openvswitch/ovn-scale-test#110]
Hello, I'm new to ovn-scale-test.
I followed the tutorial but got stuck with the bellow error when I run
ansible-playbook  -i ansible/inventory/ovn-hosts ansible/site.yml -e action=deploy

failed: [11.11.11.11-> 11.11.11.11](item=[0, '172.16.200.10']) => {"failed": true, "item": [0, "172.16.200.10"], "msg": "`docker-py
` doesn't seem to be installed, but is required for the Ansible Docker module."}

I did install docker-py by running:
pip install -U docker-py

These are my system specifications:
Ubuntu 4.4.0-34-generic
Docker version 1.11.2, build b9f10c9
Python 2.7.12

Please advice,

Thanks

**Comment by huikang** [comment]
If you login as a root, please download the ovn-scale-test repo in /root/ovn-scale-test

**Comment by muradkablan** [comment]
Thank you! That solved the problem.
