### ISSUE TITLE
pure-ovn: same ip address in multiple containers?

### ISSUE THREAD

**Issue by flavio-fernandes** [openvswitch/ovn-scale-test#117]
Hello @huikang @l8huang and @mestery,

It is very possible that I'm not looking at this the right way, but after deploying pure-ovn containers, via ".../ci/scale-pure-ovn-hosts.sh", it seems that the containers are configured
with addresses that are not unique. Does it mean all of them share the same network namespace?

See [this gist](https://gist.github.com/f98a8e35e88b7cad1b43cb77dfc0cb42) -- or below -- for the output.

Assuming that is working as expected; and if there is a doc or a piece of code that talks about
this, please forward it to me!

Thanks,
# 

<pre>
vagrant@pureovn:~$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS               NAMES
952ee145831b        ovn-scale-test-ovn   "ovn_set_chassis 172."   27 hours ago        Up 27 hours                             sandbox-172.16.200.14
403d0150b91e        ovn-scale-test-ovn   "ovn_set_chassis 172."   27 hours ago        Up 27 hours                             sandbox-172.16.200.13
8f76eeec9c1b        ovn-scale-test-ovn   "ovn_set_chassis 172."   27 hours ago        Up 27 hours                             sandbox-172.16.200.12
65cb610cb928        ovn-scale-test-ovn   "ovn_set_chassis 172."   27 hours ago        Up 27 hours                             sandbox-172.16.200.11
352ea12d2df5        ovn-scale-test-ovn   "ovn_set_chassis 172."   27 hours ago        Up 27 hours                             sandbox-172.16.200.10
8c3298e8a3bf        ovn-scale-test-ovn   "ovn-sandbox-northd.s"   27 hours ago        Up 27 hours                             ovn-northd
97db778bd646        ovn-scale-test-ovn   "ovn-sandbox-south-ov"   27 hours ago        Up 27 hours                             ovn-south-database
57ef825504ec        ovn-scale-test-ovn   "ovn-sandbox-north-ov"   27 hours ago        Up 27 hours                             ovn-north-database
vagrant@pureovn:~$
vagrant@pureovn:~$
vagrant@pureovn:~$ for cid in $(docker ps -q) ; do docker inspect --format='{{.Name}} - {{.Path}}' $cid ; docker exec $cid ip a ; echo --- ; done
/sandbox-172.16.200.14 - ovn_set_chassis
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
/sandbox-172.16.200.13 - ovn_set_chassis
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
/sandbox-172.16.200.12 - ovn_set_chassis
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
/sandbox-172.16.200.11 - ovn_set_chassis
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
/sandbox-172.16.200.10 - ovn_set_chassis
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
/ovn-northd - ovn-sandbox-northd.sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
/ovn-south-database - ovn-sandbox-south-ovsdb.sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
/ovn-north-database - ovn-sandbox-north-ovsdb.sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever

---
vagrant@pureovn:~$
</pre>

**Comment by flavio-fernandes** [comment]
heh, it looks like I'm missing on some caveat related to the ip stack here. Let me get back to my docker docs... I can clearly see that the "ip a" command in the host system is giving me the same exact value, so this is not a per container scoped. Sorry!

<pre>
vagrant@pureovn:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1a:e9:1a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.20.100/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.10/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.11/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.12/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.13/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet 172.16.200.14/16 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1a:e91a/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:57:f4:4f:75 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:57ff:fef4:4f75/64 scope link
       valid_lft forever preferred_lft forever
vagrant@pureovn:~$
</pre>

<pre>
vagrant@pureovn:~$ for cid in $(docker ps -q) ; do docker inspect --format='{{.Name}} - {{.Path}}' $cid ; docker exec $cid ps aux | grep "ov[sn]" ; echo --- ; done
/sandbox-172.16.200.14 - ovn_set_chassis
root         1  0.0  0.0  18108  1724 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.14/16 eth0
root        56  0.0  0.0   9216  1220 ?        Ss   Aug29   0:07 ovsdb-server --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --remote=punix:/usr/local/var/run/openvswitch//db.sock conf.db
root        79  0.0  0.1 460912 10816 ?        Ssl  Aug29   1:30 ovs-vswitchd --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --enable-dummy=override
root        91  0.0  0.0  18108   792 ?        S    Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.14/16 eth0
root        92  0.0  0.0  13956  2044 ?        S    Aug29   0:00 ovn-controller --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file
---
/sandbox-172.16.200.13 - ovn_set_chassis
root         1  0.0  0.0  18104  1724 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.13/16 eth0
root        49  0.0  0.0   9216  1220 ?        Ss   Aug29   0:06 ovsdb-server --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --remote=punix:/usr/local/var/run/openvswitch//db.sock conf.db
root        72  0.0  0.0 460912  7376 ?        Ssl  Aug29   1:29 ovs-vswitchd --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --enable-dummy=override
root        84  0.0  0.0  18104   792 ?        S    Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.13/16 eth0
root        85  0.0  0.0  13956  2044 ?        S    Aug29   0:00 ovn-controller --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file
---
/sandbox-172.16.200.12 - ovn_set_chassis
root         1  0.0  0.0  18104  1724 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.12/16 eth0
root        43  0.0  0.0   9216  1224 ?        Ss   Aug29   0:07 ovsdb-server --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --remote=punix:/usr/local/var/run/openvswitch//db.sock conf.db
root        66  0.0  0.1 460912  8800 ?        Ssl  Aug29   1:29 ovs-vswitchd --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --enable-dummy=override
root        78  0.0  0.0  18104   792 ?        S    Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.12/16 eth0
root        79  0.0  0.0  13956  2040 ?        S    Aug29   0:00 ovn-controller --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file
---
/sandbox-172.16.200.11 - ovn_set_chassis
root         1  0.0  0.0  18104  1724 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.11/16 eth0
root        37  0.0  0.0   9216  1220 ?        Ss   Aug29   0:07 ovsdb-server --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --remote=punix:/usr/local/var/run/openvswitch//db.sock conf.db
root        60  0.0  0.1 460912  9232 ?        Ssl  Aug29   1:28 ovs-vswitchd --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --enable-dummy=override
root        72  0.0  0.0  18104   792 ?        S    Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.11/16 eth0
root        73  0.0  0.0  13956  2048 ?        S    Aug29   0:00 ovn-controller --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file
---
/sandbox-172.16.200.10 - ovn_set_chassis
root         1  0.0  0.0  18104  1728 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.10/16 eth0
root        31  0.0  0.0   9228  1236 ?        Ss   Aug29   0:07 ovsdb-server --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --remote=punix:/usr/local/var/run/openvswitch//db.sock conf.db
root        54  0.0  0.1 460912  8256 ?        Ssl  Aug29   1:29 ovs-vswitchd --detach --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --enable-dummy=override
root        66  0.0  0.0  18104   796 ?        S    Aug29   0:00 /bin/bash /bin/ovn_set_chassis 172.16.20.100/16 172.16.200.10/16 eth0
root        67  0.0  0.0  13956  2036 ?        S    Aug29   0:00 ovn-controller --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file
---
/ovn-northd - ovn-sandbox-northd.sh
root         1  0.0  0.0  18056  1664 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn-sandbox-northd.sh 172.16.20.100/16 eth0
root        36  0.0  0.0  18056   752 ?        S    Aug29   0:00 /bin/bash /bin/ovn-sandbox-northd.sh 172.16.20.100/16 eth0
root        37  0.0  0.0   9320  1144 ?        S    Aug29   0:00 ovn-northd --no-chdir --pidfile -vconsole:off -vsyslog:off -vfile:info --log-file --log-file=/usr/local/var/run/openvswitch/ovn-northd.log --ovnnb-db=unix:/usr/local/var/run/openvswitch/ovnnb_db.sock --ovnsb-db=unix:/usr/local/var/run/openvswitch/ovnsb_db.sock
---
/ovn-south-database - ovn-sandbox-south-ovsdb.sh
root         1  0.0  0.0  18044  1644 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn-sandbox-south-ovsdb.sh 172.16.20.100/16 eth0
root        31  0.0  0.0  18048   752 ?        S    Aug29   0:00 /bin/bash /bin/ovn-sandbox-south-ovsdb.sh 172.16.20.100/16 eth0
root        32  0.0  0.0   9224  1408 ?        S    Aug29   0:09 ovsdb-server --no-chdir --pidfile=ovsdb-server-sb.pid --unixctl=ovsdb-server-sb.ctl -vconsole:off -vsyslog:off -vfile:info --log-file=ovsdb-server-sb.log --remote=punix:/usr/local/var/run/openvswitch/ovnsb_db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options conf-sb.db ovnsb.db
---
/ovn-north-database - ovn-sandbox-north-ovsdb.sh
root         1  0.0  0.0  18056  1676 ?        Ss   Aug29   0:00 /bin/bash /bin/ovn-sandbox-north-ovsdb.sh 172.16.20.100/16 eth0
root        28  0.0  0.0  18056   760 ?        S    Aug29   0:00 /bin/bash /bin/ovn-sandbox-north-ovsdb.sh 172.16.20.100/16 eth0
root        29  0.0  0.0   9200  1412 ?        S    Aug29   0:07 ovsdb-server --no-chdir --pidfile=ovsdb-server-nb.pid --unixctl=ovsdb-server-nb.ctl -vconsole:off -vsyslog:off -vfile:info --log-file=ovsdb-server-nb.log --remote=punix:/usr/local/var/run/openvswitch/ovnnb_db.sock conf-nb.db ovnnb.db
---
vagrant@pureovn:~$
</pre>

**Comment by huikang** [comment]
@flavio-fernandes is this still an issue or can we close this? Thanks.

**Comment by flavio-fernandes** [comment]
heh, definitely not an issue... closing.
