### ISSUE TITLE
Document clarifications 

### ISSUE THREAD

**Issue by muradkablan** [openvswitch/ovn-scale-test#119]
Hello again, 
Thanks for providing ovn-scale-test. I believe it will bring a great value for the research community.
As a first time user of the tool, I faced some difficulties to install it and play with it. I think mostly due some ambiguity in the instructions. 

These are some issues I faced and I think it will be helpful to add some text to clarify them:
1- Installing and running the code as a root. 
The instructions doesn't say that you must download, install, and run the test as a root user. If you don't run as a root, you will find hard time figuring out why things go wrong.

2- ssh connections between hosts and and between containers and hosts. 
This is also related to running as root. In ansible/group_vars/all.yml there is a variable "deploy_user" and the default is "rally". I was able to deploy but couldn't run any workload and was getting ssh failure errors because my machine was using the user name rally. I had to change it to "root" and everything worked after that.

3- Docker images.
It seems that docker images used for the emulated chassis are not up to date with ovs repository. Or, to be more specific, not in synchronization with the image used to build ovn-rally container. This caused a problem if the two images contain different versions of ovs commands. 

4- Terminologies. 
- [What is farm node?](https://github.com/openvswitch/ovn-scale-test/tree/master/ansible#create-sandboxes-on-multiple-farm-nodes) And why do I have to register them as it says here 
  "In addition, to register the hosts and sandboxes in the rally-ovs database, the create-sandbox task should be executed for individual farm nodes."
- Is emulated chassis the same as sandbox?

5- What is the difference between a node that runs ovn-rally workload and one that runs rally container as mentioned [here](https://github.com/openvswitch/ovn-scale-test/tree/master/ansible#host-machine-requirements)

**Comment by huikang** [comment]
@muradkablan thanks for these valuable feedback. I will update the document.

**Comment by muradkablan** [comment]
Adding to this thread, 
Do you have instructions on how to create a workload? Which files need to be changed and/or added? 
For example, if I want to create a new workload"create_and_connect_real_chassis.json" 
Do I manually have to write that file and added to workload directory?

**Comment by huikang** [comment]
@muradkablan as I have updated ansible/README, can we close this issue now?

**Comment by muradkablan** [comment]
Yes. Thanks for the updated. I'll create an issue or update this one if I find anything needs to be clarified.
