### ISSUE TITLE
Make localnet port creation optional in _create_networks()

### ISSUE THREAD

**Issue by hzhou8** [openvswitch/ovn-scale-test#134]
Now that the logical router is added to the test, _create_neworks() should be refactored to be able to disable localnet port creation in lrouter related scenarios. L2 scenarios should still keep the localnet port as default behavior.

With localnet port, a lswitch behaves in bridge mode instead of overlay mode. This may have little impact on control-plane scalability based on current implementation, but could be huge impact in the future if we try to optimize the bridge mode by not installing overlay related flows for bridged L2 datapaths.

**Comment by huikang** [comment]
@hzhou8 thanks for creating this to track this issue

**Comment by huikang** [comment]
@hzhou8 Could you help me to understand the issue in more detail?
1. what is the command to disable localnet port creation with lrouter? Any example will be very helpful.
2. When you say "optimize the bridge mode by not installing overlay related flows for bridged L2 datapaths", do you mean the optimization is made to logical switch or logical router? Thanks.

**Comment by noah8713** [comment]
We already have code support for the same. In network_create_args , skip  passing physical_network while running the test and it will skip creating localnet ports. Verified and it can be closed
