### ISSUE TITLE
Missing a sample file of creating sandboxes on multiple farms

### ISSUE THREAD

**Issue by huikang** [openvswitch/ovn-scale-test#16]
There is [file](https://github.com/openvswitch/ovn-scale-test/blob/master/samples/tasks/scenarios/ovn-sandbox/create_sandbox.json) shows how to create sandboxes on single farm node after deployment.
However, it is unclear how to create sandboxes if multiple farm nodes are registered.

**Comment by l8huang** [comment]
Sorry for replay this issue so late. 

Please see PR https://github.com/openvswitch/ovn-scale-test/pull/17.

The basic idea is simple, and the key point is change 'farm' field' to the farm node on which you want to create sandboxes. 

If you need to create a lot of sandboxes, and finish it ASAP, you can run rally-ovs commands on different console at same time.

**Comment by huikang** [comment]
Lei, thanks for your comment. Let me close this and have discussion in #17
