### ISSUE TITLE
Merge code from ovs-scale-cicd

### ISSUE THREAD

**Issue by mestery** [openvswitch/ovn-scale-test#24]
Folks, I have a repository [here](https://github.com/mestery/ovn-scale-cicd) which has some automation around the ansible done in the ovn-scale-test repository. I'd like to merge this back into the ovn-scale-test repository, but I'd like feedback on where to merge it. The idea is this can be done to automate the ansible stuff here in a CI/CD environment. We'll be implementing this downstream in our IBM Public Cloud CI/CD, and I'd like to get this implemented upstream here as well eventually.

So feedback on where this lives is greatly appreciated!

**Comment by mestery** [comment]
@l8huang @huikang @hzhou8 Comments appreciated here please!

**Comment by huikang** [comment]
Nice work. We do need a CI/CD for ovn-scale-test. I will look at the repo and add comments soon.

**Comment by huikang** [comment]
@mestery my thoughts about the CI/CD for this ovn-scale-test repo.
- The initial purpose of this CI/CD script is to run some smoke test to ensure future commit will not break the existing working system. So the shell scripts from ovs-scale-cicd should be imported to the ovn-scale-test.
- In #10 , we considered using travis-ci for the smoke test; I have started working on [this](https://github.com/huikang/ovn-scale-test/tree/travis-ci-ansible). All we need to add are a .travis.yml and some scripts to run the test as in @mestery 's repo. So Kyle, do you think you could create a branch and customize your scripts to run in travis-ci environment. This will be helpful to our future development. Thanks.

**Comment by mestery** [comment]
@huikang: I will go ahead and submit a PR to merge the ovn-scale-cid repo into the ovn-scale-test repository (unless we want to just create another repository). I will import it at the top-level and we can comment there.

Regarding travis CI, yes, I can take a peek at that! I am traveling a bit this week, but will have time to do this.

**Comment by huikang** [comment]
Sounds great.

BTW, the reason we may not need the ansible fold from https://github.com/mestery/ovn-scale-cicd/tree/master/ansible is that these variables can always be added by "-e" or generated on the machines in CI environment at run time, which can override the default values.

**Comment by mestery** [comment]
This can be closed as the code was merged.
