### ISSUE TITLE
ovn-scale-test requires non-system installation of rally

### ISSUE THREAD

**Issue by huikang** [openvswitch/ovn-scale-test#3]
Hi, Lei
I found two unclear places in the ovn rally installation guide.
- Since system-wide ovn-scale-test is not supported yet [1], installing rally should be done without root privileged. I suggest to add some note in this section [2]
- install_rally.s pulls the repo into the the directory of /home/{user}/rally [2]. Therefore, "git clone https://github.com/l8huang/rally.git" should be executed at the a different place other than /home/{user}/. If this is the case, I suggest add some note here as well.

My two cents. Thanks. - Hui

[1] https://github.com/openvswitch/ovn-scale-test/blob/master/doc/source/install.rst#install-ovn-scale-test
[2] https://github.com/openvswitch/ovn-scale-test/blob/master/doc/source/install.rst#install-rally

**Comment by l8huang** [comment]
- System-wide installation is fixed
- doc is updated

Thanks for your suggestions. 
Changes are in https://github.com/openvswitch/ovn-scale-test/pull/5 
Please help to review.

**Comment by huikang** [comment]
Thanks for your quick fix. I will test #5 and get back to you later today. - Hui

**Comment by huikang** [comment]
The issue is fixed by #5. I will close it when #5 gets merged.

**Comment by huikang** [comment]
thanks for solving the issue.
