### ISSUE TITLE
ovn-scale-test-ovn gone from docker repository

### ISSUE THREAD

**Issue by mestery** [openvswitch/ovn-scale-test#74]
I'm seeing this as of today:

TASK [ovn : start OVN northbound database] *************************************
fatal: [192.168.0.37]: FAILED! => {"changed": false, "changes": ["{\"status\":\"Pulling repository docker.io/library/ovn-scale-test-ovn\"}\r\n", "{\"errorDetail\":{\"message\":\"
Error: image library/ovn-scale-test-ovn not found\"},\"error\":\"Error: image library/ovn-scale-test-ovn not found\"}\r\n"], "failed": true, "msg": "Unrecognized status from pull
.", "status": ""}
        to retry, use: --limit @ansible/site.retry

PLAY RECAP *********************************************************************
192.168.0.37               : ok=12   changed=2    unreachable=0    failed=1

Due to this, ovn-scale-test seems to fail.

**Comment by mestery** [comment]
@huikang Did something change with your docker repository here?

**Comment by huikang** [comment]
@mestery I will submit a PR to fix this

**Comment by huikang** [comment]
The root cause of the error is because the configflags is not consumed by building Dockerfile

https://travis-ci.org/huikang/ovn-scale-test/builds/145702068#L2068
https://travis-ci.org/huikang/ovn-scale-test/builds/145702068#L4419

**Comment by mestery** [comment]
@huikang Ack, I can fix this tonight unless I see a PR from you.

**Comment by mestery** [comment]
Closing as this is fixed now.
