### ISSUE TITLE
can not use return in a non-function shell script

### ISSUE THREAD

**Issue by huikang** [openvswitch/ovn-scale-test#79]
See the error message in travis-ci [job](https://travis-ci.org/openvswitch/ovn-scale-test/builds/145714878#L5267).

The error is caused by [this line](https://github.com/openvswitch/ovn-scale-test/blob/master/ci/scale-run.sh#L44).

**Comment by mestery** [comment]
This is fixed by PR75, so lets merge that one! :)

**Comment by mestery** [comment]
https://github.com/openvswitch/ovn-scale-test/pull/75

**Comment by huikang** [comment]
merged #75
