### ISSUE TITLE
travis-ci job failed in rally-ovs

### ISSUE THREAD

**Issue by huikang** [openvswitch/ovn-scale-test#86]
broken after #65 

https://travis-ci.org/openvswitch/ovn-scale-test/builds/146386945#L5867

**Comment by mestery** [comment]
@huikang Yes, we need to have things fail if the rally jobs fail. I was planning on looking at adding some support there, but I won't have time for a few days, so please, if you have time, send a PR and I'll review. Thanks!

**Comment by huikang** [comment]
@mestery sure; I will submit PR tonight or tomorrow.
